default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
    -   id: remove-crlf
        exclude_types: [batch]
        exclude: mvnw.cmd
    -   id: remove-tabs
        args: [ --whitespaces-count=2 ]
-   repo: https://github.com/extenda/pre-commit-hooks
    rev: v0.11.0
    hooks:
    -   id: google-java-formatter
    -   id: commitlint
        stages: [commit-msg]
-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
